version: "3.8"
services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - '3000:3000'
  backend:
    build: ./backend
    container_name: backend
    ports:
      - '2019:2019'
    stdin_open: true
    tty: true